/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  StCountrylist as StCountrylist
} from './components/st-countrylist/st-countrylist';

declare global {
  interface HTMLStCountrylistElement extends StCountrylist, HTMLStencilElement {
  }
  var HTMLStCountrylistElement: {
    prototype: HTMLStCountrylistElement;
    new (): HTMLStCountrylistElement;
  };
  interface HTMLElementTagNameMap {
    "st-countrylist": HTMLStCountrylistElement;
  }
  interface ElementTagNameMap {
    "st-countrylist": HTMLStCountrylistElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "st-countrylist": JSXElements.StCountrylistAttributes;
    }
  }
  namespace JSXElements {
    export interface StCountrylistAttributes extends HTMLAttributes {
      highlighted?: string;
      name?: string;
      selected?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
